# **Working with NumPy**

You are to only write/modify the code in between consecutive `# < START >` and `# < END >` comments. 
```python
"Don't modify any code here"

# < START >
"YOUR CODE GOES HERE!"
# < END >

"Don't modify any code here"
```

<!---Need to include clarification about arrays?-->

**Start by running the below cell, to import the NumPy library.**

In [6]:
import numpy as np

### **Initializating Arrays**
NumPy offers multiple methods to create and populate arrays
- Create a $2\times3$ array identical to
$\begin{bmatrix}
1 & 2 & 4\\
7 & 13 & 21\\
\end{bmatrix}$, and assign it to a variable `arr`.  

In [15]:
# < START >
arr = np.array([1,2,4,7,13,21])
arr = np.array([[1, 2, 4], [7, 13, 21]])
# < END >

print(arr)
print("Shape:", arr.shape)

[[ 1  2  4]
 [ 7 13 21]]
Shape: (2, 3)


You should be able to see that the `shape` property of an array lets you access its dimensions.  
For us, this is a handy way to ensure that the dimensions of an array are what we expect, allowing us to easily debug programs.

- Initialize a NumPy array `x` of dimensions $2\times3$ with random values.  
Do not use the values of the dimensions directly, instead use the variables provided as arguments.
<details>
  <summary>Hint</summary>
  <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html#numpy-random-randn">np.random.randn()</a>
</details>

In [16]:
n_rows = 2
n_columns = 3

# <START>
x = np.random.randn(n_rows, n_columns)
# <END>

print(x)

[[ 0.13365571  0.0193408  -0.31581762]
 [ 0.30710139 -0.66156224 -0.6370936 ]]


A few more basic methods to initialize arrays exist.
Feel free to read up online to complete the code snippets.

In [18]:
# < START >
# Initialize an array ZERO_ARR of dimensions (4, 5, 2) whose every element is 0
ZERO_ARR = np.zeros((4, 5, 2))
# < END >

print(ZERO_ARR)

# < START >
# Initialize an array ONE_ARR of dimensions (4, 5, 2) whose every element is 1
ONE_ARR = np.ones((4, 5, 2))
# < END >

print(ONE_ARR)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


You can also transpose arrays (same as with matrices), but a more general and commonly used function is the `array.reshape()` function.

$$
\begin{bmatrix}
a & d\\
b & e\\
c & f\\
\end{bmatrix}
\xleftarrow{\text{.T}}
\begin{bmatrix}
a & b & c\\
d & e & f\\
\end{bmatrix}
\xrightarrow{\text{.reshape(3, 2)}}
\begin{bmatrix}
a & b\\
c & d\\
e & f\\
\end{bmatrix}
\xrightarrow{\text{.reshape(6,1)}}
\begin{bmatrix}
a\\b\\c\\d\\e\\f\\
\end{bmatrix}
$$
`reshape` is commonly used to flatten data stored in multi-dimensional arrays (ex: a 2D array representing a B/W image)

- Try it out yourself:

In [19]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

# < START >
# Create a new array y_transpose that is the transpose of matrix y
y_transpose = y.T
# < END >

print(y_transpose)

# < START >
# Create a new array y_flat that contains the same elements as y but has been flattened to a column array
y_flat = y.flatten()
# < END >

print(y_flat)

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


- Create a `y` with dimensions $3\times1$ (column matrix), with elements $4,7$ and $11$.  
$$y = \begin{bmatrix}
4\\
7\\
11
\end{bmatrix}$$  

In [26]:
# <START>
# Initialize the column matrix here
y = np.array([[4], [7], [11]])
# <END>

assert y.shape == (3, 1)
# The above line is an assert statement, which halts the program if the given condition evaluates to False.
# Assert statements are frequently used in neural network programs to ensure our matrices are of the right dimensions.

print(y)

# <START>
# Multiply both the arrays here
z = np.dot(arr, y)
# <END>

assert z.shape == (2, 1)

print(z)

[[ 4]
 [ 7]
 [11]]
[[ 62]
 [350]]


### **Indexing & Slicing**
Just like with normal arrays, you can access an element at the `(i,j)` position using `array[i][j]`.  
However, NumPy allows you to do the same using `array[i, j]`, and this form is more efficient and simpler to use.
<details>
<summary><i>(Optional) Why is it more efficient?</i></summary>
The former case is more inefficient as a new temporary array is created after the first index i, that is then indexed by j.
</details>

```python
x = np.array([[1,3,5],[4,7,11],[5,10,20]])

x[1][2] #11
x[1,2]  #11 <-- Prefer this
```

Slicing is another important feature of NumPy arrays. The syntax is the same as that of slicing in Python lists.
  We pass the slice as

```python
  sliced_array = array[start:end:step]
  # The second colon (:) is only needed
  # if you want to use a step other than 1
```
By default, `start` is 0, `end` is the array length (in that dimension), and `step` is 1.
Remember that `end` is not included in the slice.

  Implement array slicing as instructed in the following examples



In [27]:
x = np.array([4, 1, 5, 6, 11])

# <START>
# Create a new array y with the middle 3 elements of x
y = x[1:4]
# <END>

print(y)

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# <START>
# Create a new array w with alternating elements of z
w = z[::2]
# <END>

print(w)

[1 5 6]
[1 3 5 7 9]


A combination of indexing and slicing can be used to access rows, columns and sub-arrays of 2D arrays.

```python
arr = np.array([
          [1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

print(arr[0])       #[1 2 3]
print(arr[:,2])     #[3 6 9]
print(arr[0:2,0:2]) #[[1 2]
                    # [4 5]]
```

In [28]:
arr_2d = np.array([[4, 5, 2],
          [3, 7, 9],
          [1, 4, 5],
          [6, 6, 1]])

# <START>
# Create a 2D array sliced_arr_2d that is of the form [[5, 2], [7, 9], [4, 5]]
sliced_arr_2d = arr_2d[0:3, 1:]
# <END>

print(sliced_arr_2d)

[[5 2]
 [7 9]
 [4 5]]


### **Broadcasting**

This feature allows for flexibility in array operations. It lets us implement highly efficient algorithms with minimal use of memory.

In [29]:
arr1 = np.array([1, 2, 3, 4])
b = 1

# <START>
# Implement broadcasting to add b to each element of arr1
arr1 += b 
# <END>

print(arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[4],
                 [5]])

# <START>
# Multiply each element of the first row of arr2 by 4 and each element of the second row by 5, using only arr2 and arr3
arr2 *= arr3
# <END>

print(arr2)

[2 3 4 5]
[[ 4  8 12]
 [20 25 30]]


### **Vectorization**

From what we've covered so far, it might not be clear as to why we need to use vectorization. To understand this, let's compare the execution times of a non-vectorized program and a vectorized one.

Your goal is to multiply each element of the 2D arrays by 3. Implement this using both non-vectorized and vectorized approaches.

In [7]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array

start_nv = time.time()

# Non-vectorized approach
# <START>
for i in range(arr_nonvectorized.shape[0]):
    for j in range(arr_nonvectorized.shape[1]):
        arr_nonvectorized[i, j] = arr_nonvectorized[i, j] * 3


# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_nonvectorized)

start_v = time.time()

# Vectorized approach
# <START>
arr_vectorized *= 3

# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(arr_vectorized)

Time taken in non-vectorized approach: 183.58349800109863 ms
Time taken in vectorized approach: 0.9961128234863281 ms


# **Working with Pandas and Matpllotlib**
Here you will use Pandas Library to analyse the Census(2011) to answer the following questions :

- How does the literacy rate for males, females, and the total population differ between urban and rural areas within each state?
    - Which state has the highest disparity between urban and rural areas. Also plot 2 graphs for male and female population showing combined literacy rates for each state.

- What is the distribution of the working population (main and marginal workers) by sector (cultivators, agricultural labourers, household industry, other workers) and gender across different states?
    - Plot a graph showing all these sectors together for top 5 employed states.

- How does the literacy rate of a district affect the population aged 0 to 6 yrs within that district ? Does there seem to be a trend ?
    - Print the top 10 most literate districts and the percentage of population that is between 0 to 6 yrs, similarly do this for 10 least literate districts.

- Does literacy rates and employment rate show any similarity in their trend? 
    - Support your argument by showing a plot of literacy rates and employment rates for each state.

- The dataset can be accessed from this gdrive link [Dataset](https://drive.google.com/drive/folders/1vU1tyqLwvU1FXr30SCzv__1G1bmiUKO_?usp=sharing)

In [2]:
import pandas as pd
from matplotlib import pyplot as plt


In [3]:
data = pd.read_csv('NDAP_REPORT_6000.csv')






# Read the CSV data into a Pandas DataFrame with error handling
try:
    data = pd.read_csv('NDAP_REPORT_6000.csv')
except FileNotFoundError:
    print("Error: File 'NDAP_REPORT_6000.csv' not found. Please check the file path.")
    exit()

# Print all column names for reference
print("Available Columns:")
print(data.columns.tolist())

# Print a summary of the data (first 20 rows and basic statistics)
print("\nData Summary (first 20 rows):")
print(data.head())
print("\nData Description (statistics):")
print(data.describe(include='all'))  # Include all data types (categorical and numerical)

# Group data by State, Location, and Sex (consider including other columns for further analysis)
try:
    grouped_data = data.groupby(['State', 'Location', 'Sex'])['Literacy Rate'].mean().unstack()
except KeyError as e:
    print(f"Error: Data seems to be missing column(s): {e}. Analysis might be incomplete.")

# Calculate disparity between urban and rural literacy rates for each sex (handle potential errors)
if 'Literacy Rate' in data.columns:
    try:
        literacy_disparity = grouped_data.diff(axis=1)
    except:
        print("Error: Unable to calculate disparity. Check if 'Literacy Rate' has valid data.")
else:
    print("'Literacy Rate' column not found. Skipping disparity calculation.")

# Find the state with the highest disparity for males and females (handle potential errors)
if 'Literacy Rate' in data.columns:
    try:
        highest_disparity_male = literacy_disparity.abs().iloc[0].idxmax()
        highest_disparity_female = literacy_disparity.abs().iloc[1].idxmax()
        print("\nState with highest disparity in male literacy rate:", highest_disparity_male)
        print("State with highest disparity in female literacy rate:", highest_disparity_female)
    except:
        print("Error: Issues encountered while finding highest disparity. Check data consistency.")

# Plot combined literacy rates by state (assuming 'State' is unique)
if 'Literacy Rate' in data.columns:
    try:
        plt.figure(figsize=(10, 6))
        grouped_data.plot(kind='bar', color=['skyblue', 'lightcoral'])
        plt.xlabel('State')
        plt.ylabel('Literacy Rate')
        plt.title('Combined Literacy Rates by State (Male & Female)')
        plt.xticks(rotation=45, ha='right')
        plt.legend(title='Sex')
        plt.tight_layout()
        plt.show()
    except:
        print("Error: Issues encountered while plotting. Check data and plot configuration.")




Available Columns:
['ROWID', 'Country', 'State lgd code', 'State', 'District lgd code', 'District', 'Sub-District lgd Code', 'Sub-District', 'ULB_RLB_Village lgd Code', 'ULB_RLB_Village', 'Rural or Urban', 'Households', 'Population', 'Male population', 'Female population', 'Population in the age group 0 to 6 years', 'Male Population in the age group 0 to 6 years', 'Female Population in the age group 0 to 6 years', 'Scheduled Caste population', 'Male Scheduled Caste population', 'Female Scheduled Caste population ', 'Scheduled Tribe population', 'Male Scheduled Tribe population', 'Female Scheduled Tribe population ', 'Literate population ', 'Male literate population', 'Female literate population ', 'Illiterate population', 'Male illiterate population ', 'Female illiterate population ', 'Working population', 'Male working population', 'Female Woking population', 'Number of main workers', 'Number of male main workers', 'Number of female main worker', 'Number of main workers as cultivators